- jbdevstudio/multiple/jbdevstudio-multiple.target
- jbosstools/multiple/jbosstools-multiple.target
see commit message for p2diff output
> [JBIDE-19045] Update Tern.java and AngularJS 0.7.0

- .gitignore
- .project
- jbdevstudio/.project
- jbdevstudio/multiple/.project
- jbdevstudio/unified/.project
- jbosstools/.project
- jbosstools/multiple/.project
- jbosstools/unified/.project
target-platform.parent
target-platform.jbosstools
target-platform.jbosstools.multiple
target-platform.jbosstools.unified
target-platform.jbdevstudio
target-platform.jbdevstudio.multiple
target-platform.jbdevstudio.unified
> [JBIDE-19778] Project descriptor files for target-platforms repo modules

- jbdevstudio/multiple/jbdevstudio-multiple.target
- jbosstools/multiple/jbosstools-multiple.target
Use most recent Mars bits (most of RC3)
> JBIDE-20666 JBIDE-20567

- jbdevstudio/multiple/jbdevstudio-multiple.target
- jbosstools/multiple/jbosstools-multiple.target
+ Addition of the Naturist bundle
> Update to newer e4.ui (importer support for JDT and PDE)

- jbosstools/multiple/jbosstools-multiple.target
add org.jboss.reddeer.ui.feature.feature.group 1.1.0.201604261406
> JBIDE-22857 add org.jboss.reddeer.ui.feature.feature.group 1.1.0.201604261406

- jbosstools/multiple/jbosstools-multiple.target
For JBT 4.4.2.Final, update RedDeer in TP to version 1.2.1.Final.
> JBIDE-23420 Update RedDeer to 1.2.1.Final

- jbdevstudio/multiple/jbdevstudio-multiple.target
- jbdevstudio/multiple/pom.xml
- jbdevstudio/pom.xml
- jbdevstudio/unified/pom.xml
- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
Signed-off-by:...
release 4.70.0.Final TP
Signed-off-by: nickboldt <nboldt@redhat.com>
> release 4.70.0.Final TP

- jbosstools/multiple/jbosstools-multiple.target
to have them compatible with Java 8
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> JBDS-4727 - use asm bundles from integration orbit repository

- pom.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-26457 Update tycho to 1.3.0-SNAPSHOT

- jbosstools/multiple/jbosstools-multiple.target
- 2018-12M2
- Jetty 9.4.13
- WTP S-3.12.0.M2-20181101035339
> JBIDE-26388 - TP: create target platform based on Eclipse 4.10

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
- SimRel 2018-12M3
- m2e-apt 1.5.1
- m2eclipse-tycho 0.9.0
- dtp 1.1.4.103.20181206
- tm 4.5.1.201811011802
- jetty 9.4.14
- webtools 3.12.0.M3
- docker 4.1.0.201811292300
- testng 6.14.0
- springide 3.9.6
- RedDeer 2.4.0.RC1
> JBIDE-26477 - Update 4.11.0.AM1 TP

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-26505 - webservices compilation errors on Java11+

- pom.xml
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-26516 Update tycho to 1.3.0

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-26565: Update 4.11.0.Final TP

- jbosstools/multiple/jbosstools-multiple.target
- SimRel 2019-03RC1
- Orbit R20190226160451
- m2e-apt 1.5.1
- mylyn-github 5.3.0
- DTP 1.14.104.201903081442
- tm 4.5.100.201901312305
- Jetty 9.4.15
- Docker 4.3.0.201903062211
- SWTBot 2.7.0
- TestNG 6.14.3
- SpringIDE 3.9.7
> JBIDE-26565: Update TP for 4.11.0.Final

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> Prepare TP for 4.12.0.AM1 / 12.12.0.AM1

- jbosstools/multiple/jbosstools-multiple.target
- Docker Tooling 4.3.0.201904031802
> JBIDE-26622: Update 4.12.0.AM1 TP

- pom.xml
> Switch to Tycho 1.4.0

- jbosstools/multiple/jbosstools-multiple.target
- SimRel 2019-06.M1
Signed-off-by: Jeff MAURY <jeffmaury@localhost.localdomain>
> JBIDE-26622: Update 4.12.0.AM1 target platform

- jbosstools/multiple/jbosstools-multiple.target
- Simrel 2019-06.M220190510-1000-Simrel.2019-06.M2
- WebTools S-3.14.0.M2-20190507042910
> JBIDE-26629: Update 4.12.0.AM1 TP to 2019-06.M2

- jbosstools/multiple/jbosstools-multiple.target
- SimRel 2019-06.M3
- Orbit 20190622
- m2eclipse-archiver 0.17.4
- mylyn-github 5.4.0.20190522
- mylyn 3.24.3
- DTP 1.14.105.20190603
- tm 4.5.100.201904091701
- jetty 9.4.18.v20190429
- webtools S-3.14.0.M3-20190528041652
- docker 4.3.0.201905290238
- RedDeer 2.6.0.M3
- cameltooling 1.0.0.201905161153
> JBIDE-26649: Update 4.12.0.AM1 TP to 2019-06.M3

- jbosstools/multiple/jbosstools-multiple.target
cameltooling 1.0.0.201907261207
lsp4e 0.11.0.201907261639
webtools 3.15.0.M1-20190717080107
mylyn 3.25.0.v20190328-1711
orbit S20190709113129
simrel 2019-09.M1
> JBIDE-26715: Update 4.13.0.AM1 Target Platform

- jbosstools/multiple/jbosstools-multiple.target
added :
camel-lsp-client 1.0.0.201908021412
lsp4e 0.11.0.201908151340
docker 4.4.0.201908091806
webtools 3.15.0.M2
jetty 9.4.20.v20190813
mylyn-github 5.4.0.201906121030
simrel 2019-09.M2
orbit S20190726194335
> JBIDE-26717 : Update 4.13.AM1 for 2019-09.M2

- jbosstools/multiple/jbosstools-multiple.target
SimRel 2019-09.M3
Mylyn-github 5.5.0.201908280940-m3
WebTools 3.15.0.M3
docker 4.4.0.201908300008
lsp4e 0.11.0.201908201332
cameltooling 1.0.0.201908230805
reddeer 2.7.0.M3
swtbot 2.9.0.201908061818
orbit S20190819183153
> JBIDE-26800 : Update 4.13.AM1 for 2019-09.M3

- jbosstools/multiple/jbosstools-multiple.target
Reverts jbosstools/jbosstools-target-platforms#335
> Revert "JBIDE-26843: update Egit for nodeclipse"

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> Prepare TP for 4.14.0.AM1 / 12.14.0.AM1

- README.adoc
> Migrating issues.jboss.org --> issues.redhat.com

- pom.xml
> JBIDE-26908: Switch to tycho 1.5.1

- jbosstools/multiple/jbosstools-multiple.target
Added Apache commons-exec as it's used by odo implementation
> JBIDE-27010: Add odo based application explorer

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> Prepare TP for 4.14.0.Final / 12.14.0.Final

- pom.xml
> JBIDE-27014: switch to tycho 1.6.0

- jbosstools/multiple/jbosstools-multiple.target
added linux tools 4.5.1
switched to https
> JBIDE-26973 : move google.inject to base Target Platform

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-26973 : use wilwebdeveloper proper site with sources

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-26973 : added wildwebdeveloper 0.8.2

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-27089 : fix build

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> Prepare TP for 4.15.0.Final / 12.15.0.GA

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
updated wildwebdeveloper to 0.9.0
> Prepare TP for 4.16.0.AM1 / 12.16.0.AM1

- pom.xml
> JBIDE-27208: switch to tycho 1.7.0

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-27253: Update 4.16.0.AM1 Target Platform for 2020-06.M2

- jbosstools/multiple/jbosstools-multiple.target
Also fix JBIDE-27296 and JBIDE-27298
> JBIDE-27290 : update TP

- jbosstools/multiple/jbosstools-multiple.target
reddeer 3.0.0
docker 4.7.0.202006092019
jgit 5.8.0.202006091008-r
simrel 20200617-1000-Simrel.2020-06
m2e 1.16.0.20200610-1735
orbit R20200529191137
> JBIDE-27290: update TP for 2020-06.RC2

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-27318: remove duplicate javax.ws.rs

- jbosstools/multiple/jbosstools-multiple.target
- Added javax.xml.soap 1.3.0 to TP
> JBIDE-27447: webservices does not compile on Java11

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-27372 : removed yedit from Target Platform

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-27466: Update 4.17.0.Final TP for 2020-09

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
also move TP requirements to use Java 11
> JBIDE-27560: Update 4.18.0.AM1 Target Platform for 2020-09

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-27560: fix for camel lsp client

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
added reddeer 3.2.0
added camel lsp client 1.0.0.202012141849
> JBIDE-27596: Update 4.18.0.Final Target Platform

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-27651: Update 4.19.0.AM1 Target Platform for 2021-03

- jbosstools/multiple/pom.xml
- pom.xml
> JBIDE-27651: fix source mirror mojo

- .github/workflows/build_test.yml
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
> Introduce GitHub Actions workflow as PR check, fixes JBIDE-27709

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
added reddeer 3.4.0
added camel-lsp-client 1.0.0.202106141251
added testng 7.4.0.202106051955
> JBIDE-27909: update tp for 4.19.1.Final

- jbosstools/multiple/pom.xml
- pom.xml
> fix p2diff generation

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28008: Update 4.21.0.Final Target Platform for 2021-09 GA

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/pom.xml
> JBIDE-26888 : Replace http access to https

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> Added m2e-apt 1.5.4

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28343: prepare 4.23.0.AM1 TP update

- .github/workflows/build_test.yml
> JBIDE-28307 : move gh actions from master to main

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-28343: Update 4.23.0.AM1 Target Platform for 2022-03 RC1

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-28343: revert quarkus-jdt to latest stable

- jbosstools/multiple/jbosstools-multiple.target
> revert jdt.ls to 0.70

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28389: Update 4.23.0.Final TP for 2022-03 GA

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28467: Update 4.24.0.AM1 Target Platform for 2021-06 M2

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-28486: fix build after TP update

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-28621: adding missing org.tukaani.xz bundle after TP update

- pom.xml
> JBIDE-28476: use latest Tycho 2.7.5

- jbosstools/multiple/jbosstools-multiple.target
> JBIDE-28642: Update 4.25.0.AM1 TP to use late m2e fixes

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
JBIDE-28644: remove m2e chromatic
> JBIDE-28635: Update TP for 2022-09

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28733: update TP for 2022-12-M2

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28808: Update TP for 2022-12

- jbosstools/multiple/jbosstools-multiple.target
- jbosstools/multiple/pom.xml
- jbosstools/pom.xml
- jbosstools/unified/pom.xml
- pom.xml
> JBIDE-28745: remove conflicting boucycastle bundle
